config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :boughts
  devise_for :users
  root to: "pages#home"
  post '/create', to: 'pages#create', as: 'create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bought.rb
class Bought < ApplicationRecord
  belongs_to :user
  belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ApplicationRecord
	has_many :boughts
	has_many :users, through: :boughts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :boughts
  has_many :tickets, through: :boughts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boughts_controller.rb
class BoughtsController < ApplicationController
  def home
  end
  def create
    @user = User.find(session[:current_user_id])
    @ticket = Ticket.find(params[:ticket_id])
    @user.tickets << @ticket
    redirect_to :root
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@tickets = Ticket.all
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:prijevoznik, :vrijeme, :kolicina)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boughts_helper.rb
module BoughtsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/boughts/home.html.erb
<h1>Boughts#home</h1>
<p>Find me in app/views/boughts/home.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Fresh tickets</h1>

<% if current_user %>

	<%= link_to 'Sign out',destroy_user_session_path, method: :delete %>

	<table>
    <thead> 
        <tr>
            <td>Bus</td>
            <td>Time</td>
            <td>Quantity</td>
            <td>Price</td>
        </tr>
    </thead>

    <tbody>
        <% @tickets.each do |ticket| %>
        <tr>
            <td><%= ticket.bus %></td>
            <td><%= ticket.time %></td>
            <td><%= ticket.quantity %></td>
            <td><%= ticket.price %></td>
            <td>
                <%= button_to 'Buy', boughts_path(bought: {user_id: current_user.id, ticket_id: ticket })%>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

<% else %>

	<table>
    <thead> 
        <tr>
            <td>Bus</td>
            <td>Time</td>
            <td>Quantity</td>
            <td>Price</td>
        </tr>
    </thead>

    <tbody>
        <% @tickets.each do |ticket| %>
        <tr>
            <td><%= ticket.bus %></td>
            <td><%= ticket.time %></td>
            <td><%= ticket.quantity %></td>
            <td><%= ticket.price %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<p>To buy tickets, sign in first</p>

<%= link_to 'Sign up', new_user_registration_path %>

<%= link_to 'Sign in', new_user_session_path %>

<% end %>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :prijevoznik %>
    <%= form.text_field :prijevoznik %>
  </div>

  <div class="field">
    <%= form.label :vrijeme %>
    <%= form.datetime_select :vrijeme %>
  </div>

  <div class="field">
    <%= form.label :kolicina %>
    <%= form.number_field :kolicina %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Prijevoznik</th>
      <th>Vrijeme</th>
      <th>Kolicina</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.prijevoznik %></td>
        <td><%= ticket.vrijeme %></td>
        <td><%= ticket.kolicina %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prijevoznik:</strong>
  <%= @ticket.prijevoznik %>
</p>

<p>
  <strong>Vrijeme:</strong>
  <%= @ticket.vrijeme %>
</p>

<p>
  <strong>Kolicina:</strong>
  <%= @ticket.kolicina %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>